export default {
    products: [
    {
        _id:'123',
        name: "Benelli 502c 0km Cycles Motoshop",
        cateogory: "Moto",
        image: "/images/Benelli.jpg",
        price: 1219000,
        brand: "Benelli",
        rating: 4.5,
        numReviews: 10,
        countInStock: 4,
    },
    {
        _id:'124',
        name: "Yamaha Crypton 110",
        cateogory: "Moto",
        image: "/images/Yamaha.jpg",
        price: 182100,
        brand: "Yamaha",
        rating: 4.5,
        numReviews: 10,
        countInStock: 3,
    },
    {
        _id:'125',
        name: "Zanella Zb Full 110",
        cateogory: "Moto",
        image: "/images/Zanella.jpg",
        price: 96990,
        brand: "Zanella",
        rating: 4.5,
        numReviews: 10,
        countInStock: 3,
    },
    {
        _id:'126',
        name: "Yamaha Fz25",
        cateogory: "Moto",
        image: "/images/yamahafz.jpg",
        price: 568000,
        brand: "Yamaha",
        rating: 4.9,
        numReviews: 5,
        countInStock: 13,
    },
    {
        _id:'127',
        name: "Bajaj Ns 160",
        cateogory: "Moto",
        image: "/images/bajaj.png",
        price: 269990,
        brand: "Bajaj",
        rating: 3.2,
        numReviews: 14,
        countInStock: 10,
    },
    {
        _id:'128',
        name: "Benelli Tnt 135",
        cateogory: "Moto",
        image: "/images/benellitnt.jpg",
        price: 302000,
        brand: "Benelli",
        rating: 4.2,
        numReviews: 8,
        countInStock: 2,
    },
]
}